### ISSUE TITLE
Divide by zero error when using explicit mask

### ISSUE THREAD

**Issue by cjl2007** [ME-ICA/tedana#513]
Hi all - I am experiencing the following error, which occurs when combining data with voxelwise T2* estimates, and only if I specify an explicit mask.

..."ZeroDivisionError: Weights sum to zero, can't be normalized"

It seems that this could be related to the issue raised here? (https://neurostars.org/t/fmriprep-to-tedana/2685/12).

EDIT: After a bit of troubleshooting, I have noticed that I don't get a divide by zero error when specifying loglin as the curvefit method.

**Comment by handwerkerd** [comment]
Are you just trying to optimally combine data or is this error appearing when you're trying to run denoising? If this appears during denoising, it might be related to #490 & the in-progress fix #491

**Comment by cjl2007** [comment]
I am not just trying to optimally combine data. I am running tedana with the intent to denoise the data. This error just happens to occur around the oc step.

**Comment by handwerkerd** [comment]
#490 is about an error when a given mask includes voxels with no data. When those time series with zeros are processed, there can be a zero division error. It's possible the bug you mention here happens in the same place or is a similar issue at another point in the code. Could you share the screen output lines above the ZeroDevisionError to better localize when this error appears?

**Comment by cjl2007** [comment]
INFO:tedana.combine:Optimally combining data with voxel-wise T2 estimates
Traceback (most recent call last):
  File "/home/charleslynch/miniconda3/envs/me/bin/tedana", line 10, in <module>
    sys.exit(_main())
  File "/home/charleslynch/miniconda3/envs/me/lib/python3.7/site-packages/tedana/workflows/tedana.py", line 640, in _main
    tedana_workflow(**vars(options))
  File "/home/charleslynch/miniconda3/envs/me/lib/python3.7/site-packages/tedana/workflows/tedana.py", line 456, in tedana_workflow
    data_oc = combine.make_optcom(catd, tes, mask, t2s=t2s_full, combmode=combmode)
  File "/home/charleslynch/miniconda3/envs/me/lib/python3.7/site-packages/tedana/combine.py", line 177, in make_optcom
    combined = _combine_t2s(data, tes, t2s)
  File "/home/charleslynch/miniconda3/envs/me/lib/python3.7/site-packages/tedana/combine.py", line 58, in _combine_t2s
    combined = np.average(data, axis=1, weights=alpha)
  File "<__array_function__ internals>", line 6, in average
  File "/home/charleslynch/miniconda3/envs/me/lib/python3.7/site-packages/numpy/lib/function_base.py", line 420, in average
    "Weights sum to zero, can't be normalized")
ZeroDivisionError: Weights sum to zero, can't be normalized

**Comment by handwerkerd** [comment]
This looks like the same issue in a different part of the code. I'm going to reference this bug in #491 so that these can hopefully be addressed together. The fundamental issue is that any function that uses volumetric data should include a test for data-less voxels that is addressed either with a descriptive error or with additional masking + a warning.

In the short-term, I suggest shrinking your mask to exclude voxels with only zeros. That should allow you to continue processing your data. If it doesn't please say so.

**Comment by cjl2007** [comment]
Great, thanks for your help and suggestion.

**Comment by cjl2007** [comment]
hi @handwerkerd - Unfortunately, modifying the explicit mask to exclude voxels with values <=0 did not resolve this error. I am curious to hear if there are any updates or new guidance for users experiencing this error, thanks again!

**Comment by tsalo** [comment]
@cjl2007 I'm happy to work on this today. The main roadblock for me is reproducing the bug. Would you be willing to share data and a mask that raise the error?

**Comment by cjl2007** [comment]
@tsalo, sorry for the delay -  For what its worth, I was able to circumvent this problem by performing a brain extraction using the mask prior to running tedana. In other words, setting all non in-mask voxels to 0 in the input data.  I am still happy to share the data / mask with you, in case its helpful to understand what was going awry in the first place.

**Comment by tsalo** [comment]
@cjl2007 I'm glad you were able to get around the problem, but I'd definitely like to squash this bug at its source. If you're willing to send me an example dataset and a failing mask, you can post a link here or email it to me at tsalo006@fiu.edu.

**Comment by tsalo** [comment]
After replicating the bug on @cjl2007's data, I believe I've identified the problem. For two voxels, with T2* values of 0.00850023 and 0.01446573, respectively, the weights evaluate to zeroes across all echoes. This is because the T2* values are too small to be evaluated:

```python
alpha = tes * np.exp(-tes / ft2s)
```

`np.exp(-13/0.0144)` --> `np.exp(-902.78)` --> `0.0`

Whether the values will evaluate to zero depends on the T2* value, the echo times, and how we store the values (e.g., float32 vs float64). I think our move should be to restrict these very-low T2* values to more reasonable values, as we do with negative or zero values, or exclude those voxels completely (see https://github.com/ME-ICA/tedana/issues/543#issuecomment-593144166).

**Comment by handwerkerd** [comment]
Sounds like a reasonable approach for resolving this bug. I'll continue the discussion at #544.

**Comment by tsalo** [comment]
Here's a reasonable solution, I think. What if we simply replace T2* in voxels where the value is too small to work?

Working from this code, we can come up with something that should keep very small T2* values small, while still returning actual values in the `np.exp` call.

https://github.com/ME-ICA/tedana/blob/ddaa4d5c9f3b6395e7b8944f79960aefbec214f0/tedana/combine.py#L45

Within our decay fitting functions, we could do the following, which would crop T2* values that are too low to a value that should work with `_compute_t2s`.

```python
# Apply a floor to T2* values given the echo times in the data
temp_arr = np.exp(-echo_times / t2s)
bad_voxels = np.any(temp_arr == 0, axis=1)
eps = np.finfo(dtype=np.float32).eps
t2s[bad_voxels] = np.min(-echo_times) / np.log(eps)
```

**Comment by jbteves** [comment]
I think that's a good solution, it's how I've handled this before in similar situations.
